//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubeAss.API.Customer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClubeAss.API.Customer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta versão da API esta obsoleta. Use uma das novas APIs disponíveis no explorer..
        /// </summary>
        public static string Deprecated {
            get {
                return ResourceManager.GetString("Deprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado, tente mais tarde!.
        /// </summary>
        public static string ERRO_Default {
            get {
                return ResourceManager.GetString("ERRO-Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Campo {0} deve conter pelo menos {1} caracteres.
        /// </summary>
        public static string ERRO_MinimumLength {
            get {
                return ResourceManager.GetString("ERRO-MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório.
        /// </summary>
        public static string ERRO_NotEmpty {
            get {
                return ResourceManager.GetString("ERRO-NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Copyright. Todos os Direitos Reservados..
        /// </summary>
        public static string PROJECT_Copyright {
            get {
                return ResourceManager.GetString("PROJECT-Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da api generica.
        /// </summary>
        public static string PROJECT_Description {
            get {
                return ResourceManager.GetString("PROJECT-Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email@email.com.br.
        /// </summary>
        public static string PROJECT_Email {
            get {
                return ResourceManager.GetString("PROJECT-Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api base para todos os novos projetos.
        /// </summary>
        public static string PROJECT_Name {
            get {
                return ResourceManager.GetString("PROJECT-Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com.br/.
        /// </summary>
        public static string PROJECT_TermsOfService {
            get {
                return ResourceManager.GetString("PROJECT-TermsOfService", resourceCulture);
            }
        }
    }
}
